title: 윤준혁
description: 개발 저장 블로그

url: https://github.com/akwesa/akwesa.github.io.git
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About me
   url: /about

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: jun022424@gmail.com
